/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops.index'
import { Route as WorkshopsWorkshopIdRouteImport } from './routes/workshops.$workshopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsWorkshopIdRoute = WorkshopsWorkshopIdRouteImport.update({
  id: '/workshops/$workshopId',
  path: '/workshops/$workshopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/staff': typeof StaffRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/staff': typeof StaffRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops': typeof WorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/staff': typeof StaffRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/chat'
    | '/feedback'
    | '/presentation'
    | '/reset-password'
    | '/resources'
    | '/staff'
    | '/api/chat'
    | '/api/health'
    | '/workshops/$workshopId'
    | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/chat'
    | '/feedback'
    | '/presentation'
    | '/reset-password'
    | '/resources'
    | '/staff'
    | '/api/chat'
    | '/api/health'
    | '/workshops/$workshopId'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/chat'
    | '/feedback'
    | '/presentation'
    | '/reset-password'
    | '/resources'
    | '/staff'
    | '/api/chat'
    | '/api/health'
    | '/workshops/$workshopId'
    | '/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  FeedbackRoute: typeof FeedbackRoute
  PresentationRoute: typeof PresentationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  StaffRoute: typeof StaffRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  WorkshopsWorkshopIdRoute: typeof WorkshopsWorkshopIdRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$workshopId': {
      id: '/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof WorkshopsWorkshopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  FeedbackRoute: FeedbackRoute,
  PresentationRoute: PresentationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  StaffRoute: StaffRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  WorkshopsWorkshopIdRoute: WorkshopsWorkshopIdRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
